name: CI workflow

# Add trigger event
on: #start listen event
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

# Add a Job
jobs:
  build: #NameAction of job
    runs-on: ubuntu-latest
    container: python:3.9-
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint with flake8
        run: |
          flake8 service --count --select=E9,F63,F7,F82 --show-cource --statistics
          flake8 service --count --max-complexity=10 --max-line-lenght=127 --statistics

      - name: Run unit test with nose
        run: nosetests -v --with-spec --spec-color --with-coverage --coverage-package=app
